project:
  type: website
  output-dir: docs

website:
  title: "ISWB 15 Hypervolume Workshop"
  navbar:
    left:

    - text: "R & Rstudio"
      href: comp.html
    - text: 'Ex 1'
      href: ex1.qmd
    - text: 'Ex 2'
      href: ex2.qmd
    - text: 'Ex 3'
      href: ex3.qmd

format:
  html:
    theme: yeti
    highlight: haddock
    css: styles.css



