---
format: html
---

# *WS01 – Hypervolume modelling: a multivariate tool for seagrass ecosystem assessments*
## Main-conveners:
W. Ryan James (Florida International University, USA) – wjames@fiu.edu

## Co-conveners: 
Rolando O. Santos (FIU), Benjamin Jones (Project Seagrass, FIU), Jennifer Rehage (FIU), Marianna Coppola (FIU), Gina Badlowski (FIU), Jonathan Rodemann (FIU) 

## About this workshop: 
Welcome to our Hypervolume workshop! The goal of this workshop is to familiarize participants with the concept of hypervolumes, case studies and applications, and how to run the analyses in R. We will start the workshop by providing background and theory on hypervolumes. We will then present multiple case studies using hypervolumes in seagrass and other ecosystems. These case studies will be followed by an interest survey and a walkthrough of the data and R code used to conduct the hypervolume analyses. R scripts and markdown/quarto files will be provided to encourage participants to conduct hypervolume analysis on their own data and promote comparative cross system studies.\

Hypervolume modelling is a flexible multivariate modelling technique based on Hutchinson’s *n*-dimensional hypervolume concept of a niche that describes the ecological requirements of an individual, species, or population in order to persist in a location. Hypervolumes are defined as a set of points that enclose all values of *n* variables in *n*-dimensional space. Advances led by Blonder and colleagues (see references) provide multivariate kernel density estimation methods that allows for construction of hypervolumes with a range of variables that expand applications of hypervolumes to a variety of ecological and evolutionary questions and processes beyond niche theory. Examples include quantifying ecosystem status following restoration, mapping the resilience of coastal habitats, and determining the impact of disturbance on trophic functioning (see resources). By leveraging the concept of hypervolumes, seagrass ecologists can gain a more nuanced and comprehensive understanding of their complex interactions and dynamics, facilitatiing conservation, management and restoration.\


## Resources
[Workshop GitHub](https://github.com/CoastalFishScience/ISBW_HVworkshop) – Website that houses data and code for our hypervolume workshop\

[Workshop slides](ISBW_HVworkshop.pdf)

### Hypervolume publications:
[Blonder et al. 2014. The n-dimensional hypervolume. Global Ecology and Biogeography](https://doi-org.ezproxy.fiu.edu/10.1111/geb.12146)\

[Blonder et al. 2018. New approaches for delineating n-dimensional hypervolumes. Methods in Ecology & Evolution](https://doi-org.ezproxy.fiu.edu/10.1111/2041-210X.12865)\

[Blonder 2017. Hypervolume concepts in niche- and trait-based ecology. Ecography](https://doi.org/10.1111/ecog.03187)\

### Case study publications: 

Hypervolume size: [Santos et al. 2022. Influence of seascape spatial pattern on the trophic niche of an omnivorous fish. Ecosphere]()\
Centroid distance: [Jones et al. 2020. Stress gradients interact with disturbance to reveal alternative states in salt marsh: Multivariate resilience at the landscape scale. Journal of Ecology](https://doi.org/10.1111/1365-2745.13552)\
Overlap: [Helsen et al. (2020). Inter‐and intraspecific trait variation shape multidimensional trait overlap between two plant invaders and the invaded communities. Oikos](https://doi.org/10.1111/oik.06919)\

### Other hypervolume examples

[James et al 2020. Assessment of food web recovery following restoration using resource niche metrics. Science of the Total Environment.](https://doi.org/10.1016/j.scitotenv.2019.134801)\

[Lesser et al. 2020. Trophic niche size and overlap decreases with increasing ecosystem productivity. Oikos](https://doi.org/10.1111/oik.07026)\

[Calhoun-Grosch et al. 2023. Trophic niche metrics reveal long-term shift in Florida Bay food webs. Ecosystems](https://doi.org/10.1007/s10021-023-00825-5)\

[Lamanna et al. 2014. Functional trait space and the latitudinal diversity gradient. Proceedings of the National Academy of Sciences of the United States of America](https://doi.org/10.1073/pnas.1317722111)\

[Laini et al. 2023. N-dimensional hypervolumes in trait-based ecology: Does occupancy rate matter?. Functional Ecology](https://doi.org/10.1111/1365-2435.14344)\

[Chen et al. 2024. Statistical inference methods for n-dimensional hypervolumes: Applications to niches and functional diversity. Methods in Ecology & Evolution](https://doi.org/10.1111/2041-210X.14310)\




